# Default settings for the helmchart
# namespace: the target namespace
namespace: webstats

# Settings for the frontend deployment
frontend:
  # The number of replicas to run
  replicas: 1
  # Application port to expose
  port: 3000

  # Liveness probe
  livenessProbe: true
  # Startup probe
  startupProbe: true

  # Backend URL
  backend_url: http://webstats-backend.webstats.svc.cluster.local:3000

  # The image to use
  image: europe-west3-docker.pkg.dev/bnbdevelopment/webstats/frontend
  # The tag to use
  tag: 1.0.0

# Settings for the backend deployment
backend:
  # The number of replicas to run
  replicas: 1
  # Application port to expose
  port: 3000
  # Prefix for the application ingress
  prefix: /api/v1

  # Liveness probe
  livenessProbe: true
  # Startup probe
  startupProbe: true

  # The image to use
  image: europe-west3-docker.pkg.dev/bnbdevelopment/webstats/backend
  # The tag to use
  tag: 1.0.0

  # Settings for the autoscaling
  autoscale:
    enabled: true
    # The minimum number of replicas to run
    minReplicas: 1
    # The maximum number of replicas to run
    maxReplicas: 10
    # The target CPU utilization percentage
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # Expose prometheus metrics
  metrics:
    enabled: true
    # Create servicemonitor crds for prometheus
    servicemonitor:
      enabled: true
      # Namespace of the servicemonitor
      namespace: monitoring

# Settings for the ingress
ingress:
  # Whether to enable the ingress
  enabled: true
  # The ingressclass to use
  ingressclass: traefik-external
  # The host to use
  host: stats.bnbdevelopment.hu

# Setting up S3 storage for GeoDB data
s3:
  # Whether to enable the S3 storage
  enabled: true
  # The secret reference to configure access and secret keys
  secret_ref: webstats-sm
  # The bucket name to use
  bucket_name: webstats-geodb
  # The bucket region to use
  bucket_region: garage
  # The bucket endpoint to use
  bucket_endpoint: http://192.168.88.77:3900
  # Filename to use
  dbname: GeoLite2-City.mmdb
