name: Deploy Helm charts to GAR

on:
  push:
    branches: [ main ]
    paths:
      - '**/Chart.yaml'
      - '**/values.yaml'
      - '**/templates/**'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GAR_LOCATION: ${{ vars.GAR_LOCATION }}
      GAR_PROJECT_ID: ${{ vars.GAR_PROJECT_ID }}
      GAR_REPOSITORY: ${{ vars.GAR_REPOSITORY }}
      OCI_REGISTRY: ${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GAR_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          access_token_lifetime: 300s

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker --quiet $GAR_LOCATION-docker.pkg.dev

      - name: Determine changed charts
        id: list
        run: |
          # Use git to find changed chart directories
          changed_charts=""
          
          # Check if we have a previous commit to compare against
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            # Compare with previous commit
            for chart_dir in */; do
              if [ -f "${chart_dir}Chart.yaml" ]; then
                if git diff --name-only HEAD~1 HEAD | grep -q "^${chart_dir}"; then
                  changed_charts="${changed_charts}${chart_dir} "
                fi
              fi
            done
          else
            # If no previous commit, check all charts (first push scenario)
            for chart_dir in */; do
              if [ -f "${chart_dir}Chart.yaml" ]; then
                changed_charts="${changed_charts}${chart_dir} "
              fi
            done
          fi
          
          # Fallback to ct if git method doesn't find anything
          if [ -z "$changed_charts" ]; then
            changed_charts=$(ct list-changed --config .github/ct.yaml | tr '\n' ' ')
          fi
          echo "changed=$changed_charts" >> $GITHUB_OUTPUT

      - name: Package and push changed charts to GAR
        if: steps.list.outputs.changed != ''
        run: |
          set -euo pipefail
          for c in ${{ steps.list.outputs.changed }}; do
            if [ ! -f "$c/Chart.yaml" ]; then
              echo "Skipping $c (no Chart.yaml)"
              continue
            fi
            echo "Packaging $c"
            helm dependency build "$c" || true
            pkg=$(helm package "$c" -d dist | awk '{print $NF}')
            echo "Pushing $pkg"
            helm push "$pkg" oci://$OCI_REGISTRY
          done

      - name: No changes
        if: steps.list.outputs.changed == ''
        run: echo "No changed charts to deploy."
